/** Sigla provincia ISTAT → regione. Include anche sigle storiche della Sardegna. */
const SIGLA_TO_REGIONE: Record<string, string> = {
  AG: "Sicilia",
  AL: "Piemonte",
  AN: "Marche",
  AO: "Valle d'Aosta",
  AP: "Marche",
  AQ: "Abruzzo",
  AR: "Toscana",
  AT: "Piemonte",
  AV: "Campania",
  BA: "Puglia",
  BG: "Lombardia",
  BI: "Piemonte",
  BL: "Veneto",
  BN: "Campania",
  BO: "Emilia-Romagna",
  BR: "Puglia",
  BS: "Lombardia",
  BT: "Puglia",
  BZ: "Trentino-Alto Adige",
  CA: "Sardegna",
  CB: "Molise",
  CE: "Campania",
  CH: "Abruzzo",
  CI: "Sardegna",
  CL: "Sicilia",
  CN: "Piemonte",
  CO: "Lombardia",
  CR: "Lombardia",
  CS: "Calabria",
  CT: "Sicilia",
  CZ: "Calabria",
  EN: "Sicilia",
  FC: "Emilia-Romagna",
  FE: "Emilia-Romagna",
  FG: "Puglia",
  FI: "Toscana",
  FM: "Marche",
  FR: "Lazio",
  GE: "Liguria",
  GO: "Friuli-Venezia Giulia",
  GR: "Toscana",
  IM: "Liguria",
  IS: "Molise",
  KR: "Calabria",
  LC: "Lombardia",
  LE: "Puglia",
  LI: "Toscana",
  LO: "Lombardia",
  LT: "Lazio",
  LU: "Toscana",
  MB: "Lombardia",
  MC: "Marche",
  ME: "Sicilia",
  MI: "Lombardia",
  MN: "Lombardia",
  MO: "Emilia-Romagna",
  MS: "Toscana",
  MT: "Basilicata",
  NA: "Campania",
  NO: "Piemonte",
  NU: "Sardegna",
  OG: "Sardegna",
  OR: "Sardegna",
  OT: "Sardegna",
  PA: "Sicilia",
  PC: "Emilia-Romagna",
  PD: "Veneto",
  PE: "Abruzzo",
  PG: "Umbria",
  PI: "Toscana",
  PN: "Friuli-Venezia Giulia",
  PO: "Toscana",
  PR: "Emilia-Romagna",
  PT: "Toscana",
  PU: "Marche",
  PV: "Lombardia",
  PZ: "Basilicata",
  RA: "Emilia-Romagna",
  RC: "Calabria",
  RE: "Emilia-Romagna",
  RG: "Sicilia",
  RI: "Lazio",
  RM: "Lazio",
  RN: "Emilia-Romagna",
  RO: "Veneto",
  SA: "Campania",
  SI: "Toscana",
  SO: "Lombardia",
  SP: "Liguria",
  SR: "Sicilia",
  SS: "Sardegna",
  SU: "Sardegna",
  SV: "Liguria",
  TA: "Puglia",
  TE: "Abruzzo",
  TN: "Trentino-Alto Adige",
  TO: "Piemonte",
  TP: "Sicilia",
  TR: "Umbria",
  TS: "Friuli-Venezia Giulia",
  TV: "Veneto",
  UD: "Friuli-Venezia Giulia",
  VA: "Lombardia",
  VB: "Piemonte",
  VC: "Piemonte",
  VE: "Veneto",
  VI: "Veneto",
  VR: "Veneto",
  VS: "Sardegna",
  VT: "Lazio",
  VV: "Calabria",
};

const NOME_TO_SIGLA: Record<string, string> = {
  agrigento: "AG",
  alessandria: "AL",
  ancona: "AN",
  aosta: "AO",
  "valle d'aosta": "AO",
  "valle daosta": "AO",
  "aosta / aoste": "AO",
  "ascoli piceno": "AP",
  "l'aquila": "AQ",
  aquila: "AQ",
  arezzo: "AR",
  asti: "AT",
  avellino: "AV",
  bari: "BA",
  bergamo: "BG",
  biella: "BI",
  belluno: "BL",
  benevento: "BN",
  bologna: "BO",
  brindisi: "BR",
  brescia: "BS",
  "barletta-andria-trani": "BT",
  "barletta andria trani": "BT",
  bolzano: "BZ",
  "bolzano / bozen": "BZ",
  "alto adige": "BZ",
  cagliari: "CA",
  campobasso: "CB",
  caserta: "CE",
  chieti: "CH",
  "carbonia-iglesias": "CI",
  "carbonia iglesias": "CI",
  caltanissetta: "CL",
  cuneo: "CN",
  como: "CO",
  cremona: "CR",
  cosenza: "CS",
  catania: "CT",
  catanzaro: "CZ",
  enna: "EN",
  "forli-cesena": "FC",
  "forli cesena": "FC",
  "forlì-cesena": "FC",
  "forlì cesena": "FC",
  ferrara: "FE",
  foggia: "FG",
  firenze: "FI",
  "fermo": "FM",
  frosinone: "FR",
  genova: "GE",
  gorizia: "GO",
  grosseto: "GR",
  imperia: "IM",
  isernia: "IS",
  crotone: "KR",
  lecco: "LC",
  lecce: "LE",
  livorno: "LI",
  lodi: "LO",
  latina: "LT",
  lucca: "LU",
  monza: "MB",
  "monza e della brianza": "MB",
  "monza-brianza": "MB",
  macerata: "MC",
  messina: "ME",
  milano: "MI",
  mantova: "MN",
  modena: "MO",
  massa: "MS",
  "massa-carrara": "MS",
  "massa carrara": "MS",
  matera: "MT",
  napoli: "NA",
  novara: "NO",
  nuoro: "NU",
  ogliastra: "OG",
  oristano: "OR",
  "olbia-tempio": "OT",
  "olbia tempio": "OT",
  palermo: "PA",
  piacenza: "PC",
  padova: "PD",
  pescara: "PE",
  perugia: "PG",
  pisa: "PI",
  pordenone: "PN",
  prato: "PO",
  parma: "PR",
  pistoia: "PT",
  "pesaro e urbino": "PU",
  "pesaro-urbino": "PU",
  pesaro: "PU",
  pavia: "PV",
  potenza: "PZ",
  ravenna: "RA",
  "reggio calabria": "RC",
  "reggio di calabria": "RC",
  "reggio emilia": "RE",
  "reggio nell'emilia": "RE",
  ragusa: "RG",
  rieti: "RI",
  roma: "RM",
  "roma capitale": "RM",
  rimini: "RN",
  rovigo: "RO",
  salerno: "SA",
  siena: "SI",
  sondrio: "SO",
  "la spezia": "SP",
  spezia: "SP",
  siracusa: "SR",
  sassari: "SS",
  "sud sardegna": "SU",
  savona: "SV",
  taranto: "TA",
  teramo: "TE",
  trento: "TN",
  torino: "TO",
  trapani: "TP",
  terni: "TR",
  trieste: "TS",
  treviso: "TV",
  udine: "UD",
  varese: "VA",
  "verbano-cusio-ossola": "VB",
  "verbano cusio ossola": "VB",
  vercelli: "VC",
  venezia: "VE",
  vicenza: "VI",
  verona: "VR",
  "medio campidano": "VS",
  viterbo: "VT",
  "vibo valentia": "VV",
};

function foldItalian(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/['’`]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function normalizeProvinciaSigla(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (/^[A-Za-z]{2}$/.test(trimmed)) {
    const sigla = trimmed.toUpperCase();
    return SIGLA_TO_REGIONE[sigla] ? sigla : null;
  }

  const folded = foldItalian(trimmed)
    .replace(
      /^(provincia( di)?|citta( metropolitana)?( di)?|libero consorzio comunale( di)?)\s+/,
      ""
    )
    .replace(/^di\s+/, "")
    .trim();
  if (!folded) return null;
  return NOME_TO_SIGLA[folded] ?? null;
}

export function regioneOfProvincia(raw: string): string | null {
  const sigla = normalizeProvinciaSigla(raw);
  if (!sigla) return null;
  return SIGLA_TO_REGIONE[sigla] ?? null;
}

export function sameProvincia(a: string, b: string): boolean {
  const left = a.trim();
  const right = b.trim();
  if (!left || !right) return false;
  if (foldItalian(left) === foldItalian(right)) return true;
  const siglaA = normalizeProvinciaSigla(left);
  const siglaB = normalizeProvinciaSigla(right);
  return Boolean(siglaA && siglaB && siglaA === siglaB);
}

export function provinciaInRegione(provincia: string, regione: string): boolean {
  const mapped = regioneOfProvincia(provincia);
  return Boolean(mapped && foldItalian(mapped) === foldItalian(regione));
}
